#!/bin/bash
cd ./scripts

if [ "$1" == "bootstrap" ]
    then 
        ./bootstrap
    exit 0
fi

if [ "$1" == "start" ]
    then
        ./start
    exit 0
fi

if [ "$1" == "stop" ]
    then 
        ./stop
    exit 0
fi

if [ "$1" == "restart" ]
    then 
        ./restart
    exit 0
fi

if [ "$1" == "version" ]
    then 
        ./version $2
    exit 0
fi

if [ "$1" == "publish" ]
    then 
        ./publish
    exit 0
fi

./app $*

cd ../