version: '3.4'
name: {{{{packageName}}}}
services:
  app:
    container_name: {{{{packageName}}}}-app
    build:
      context: .
      target: runner
    image: {{{{packageName}}}}-app-local
    ports:
      - ${VITE_PORT:-8000}:${VITE_PORT:-8000}
    volumes:
      - ./:/usr/src/app
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{{{packageName}}}}.tls=true
      - traefik.http.routers.{{{{packageName}}}}.rule=Host("{{{{packageName}}}}.docker.localhost")
      - traefik.http.services.{{{{packageName}}}}.loadbalancer.server.port=${VITE_PORT:-8000}
    networks:
      - applications
networks:
    applications:
        name: applications
        external: true