name: "Deploy config"

on:
  push:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-config:
    name: Deploy doppler config
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Prepare Terraform variables
        id: terraform_variables
        uses: henrotaym/prepare-terraform-variables-action@v3
        with:
          app_key: ${{ github.event.repository.name }}
          github_branch: ${{ github.ref }}
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ~1.5.7
      - name: Init Terraform
        working-directory: devops/infrastructure/environments/main
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.DIGITALOCEAN_SPACES_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.DIGITALOCEAN_SPACES_SECRET_ACCESS_KEY }}" \
            -backend-config="bucket=${{ secrets.DIGITALOCEAN_SPACES_TERRAFORM_STATES_BUCKET }}" \
            -backend-config="key=${{ steps.terraform_variables.outputs.trustup_app_key }}-environments-main.tfstate"
      - name: Apply Terraform infrastructure
        working-directory: devops/infrastructure/environments/main
        run: terraform apply -auto-approve
        env:
          TF_VAR_DOPPLER_ACCESS_TOKEN_USER: "${{ secrets.DOPPLER_ACCESS_TOKEN_USER }}"
          TF_VAR_TRUSTUP_APP_KEY: "${{ steps.terraform_variables.outputs.trustup_app_key }}"
